version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: cinewiki-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cinewiki_db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: